global:
  scrape_interval:      5s
  evaluation_interval:  5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'mongo'
    static_configs:
      - targets: ['mongodb-exporter:9216']

  - job_name: 'influxdb'
    static_configs:
      - targets: ['influxdb:8086']
    metrics_path: '/metrics'
    scheme: 'http'
